# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          beenpow
baseurl:        "https://beenpow.github.io"
url:            "https://beenpow.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         beenpow
  url:          https://beenpow.github.io/
  email:        beenpow@gmail.com  
  github:       beenpow
  twitter:      beenpow

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/beenpow/beenpow.github.io
